(* ::Package:: *)

(* ::Input:: *)
(*NotebookEvaluate[NotebookDirectory[]<>"functions.m"]*)
(*dashedline[\[Lambda]0_,\[Tau]0_,color_,opacity_:1]:={color,Opacity[opacity],Dashed,Line[{{\[Lambda]0,0},{\[Lambda]0,\[Tau]0}}]}*)
(*opa75=Opacity[.75];*)
(*SetOptions[Plot,PlotStyle->opa75,ImageSize->Medium,Frame->True,LabelStyle->Directive[Black],BaseStyle->{FontSize->9.5}];*)


(* ::Input:: *)
(*resetparams:=(ClearAll[\[Zeta],\[Kappa]];\[Zeta]=.25;\[Kappa]=1.15;\[Tau]D=1.1;\[Tau]F=1.2;\[Delta]1=.6;\[Delta]2=.8;)*)


(* ::Input:: *)
(*resetparams;*)
(*costratio=Plot[{\[Tau]D,*)
(*c1U[\[Delta]2,\[Tau]F],*)
(*c1D[\[Chi],\[Delta]2],*)
(*c1U[\[Delta]1,\[Tau]F],*)
(*c1D[\[Chi],\[Delta]1]*)
(*},*)
(*{\[Chi],0,1},*)
(*PlotRange->{{-.02,1.02},{.99,1.2}},*)
(*(*PlotLabel\[Rule]"Subscript[\[Delta], 1]="<>ToString[\[Delta]1]<>", Subscript[\[Delta], 2]="<>ToString[\[Delta]2],*)*)
(*PlotStyle->({opa75,#}&/@{Gray,RGBColor[0.560181, 0.691569, 0.194885],RGBColor[0.560181, 0.691569, 0.194885],RGBColor[0.647624, 0.37816, 0.614037],RGBColor[0.647624, 0.37816, 0.614037]}),*)
(*FrameLabel->{"Regional content requirement (\!\(\*SubscriptBox[\(\[Chi]\), \(R\)]\))","Cost penalty relative to compliance in D"},*)
(*Epilog-> {*)
(*Text["\!\(\*SubscriptBox[\(\[Delta]\), \(1\)]\)="<>ToString[\[Delta]1]<>", \!\(\*SubscriptBox[\(\[Delta]\), \(2\)]\)="<>ToString[\[Delta]2],{(0+1)/2,1.2},{0,1.5}],*)
(*Text["\!\(\*SuperscriptBox[\(\[Tau]\), \(D\)]\)",{0,\[Tau]D},{-1,-1}],*)
(*Text["\!\(\*SuperscriptBox[OverscriptBox[\(C\), \(~\)], \(D\)]\)(\!\(\*SubscriptBox[\(\[Chi]\), \(R\)]\),\!\(\*SubscriptBox[\(\[Delta]\), \(1\)]\))",{\[Chi],c1D[\[Chi],\[Delta]1]}/.\[Chi]->.625,{1,-1}],*)
(*Text["\!\(\*SuperscriptBox[\(\[Tau]\), \(F\)]\)\!\(\*SuperscriptBox[\(\[Omega]\), \(F\)]\)\!\(\*SubscriptBox[OverscriptBox[\(C\), \(~\)], \(U\)]\)(\!\(\*SubscriptBox[\(\[Delta]\), \(1\)]\))",{\[Chi],c1U[\[Delta]1,\[Tau]F]}/.\[Chi]->0,{-1,1.2}],*)
(*Text["\!\(\*SuperscriptBox[OverscriptBox[\(C\), \(~\)], \(D\)]\)(\!\(\*SubscriptBox[\(\[Chi]\), \(R\)]\),\!\(\*SubscriptBox[\(\[Delta]\), \(2\)]\))",{\[Chi],c1D[\[Chi],\[Delta]2]}/.\[Chi]->.903,{1,-1}],*)
(*Text["\!\(\*SuperscriptBox[\(\[Tau]\), \(F\)]\)\!\(\*SuperscriptBox[\(\[Omega]\), \(F\)]\)\!\(\*SubscriptBox[OverscriptBox[\(C\), \(~\)], \(U\)]\)(\!\(\*SubscriptBox[\(\[Delta]\), \(2\)]\))",{\[Chi],c1U[\[Delta]2,\[Tau]F]}/.\[Chi]->0,{-1,-1.1}],*)
(*dashedline[\[Chi]DNC[\[Delta]1,\[Tau]F],c1U[\[Delta]1,\[Tau]F],RGBColor[0.647624, 0.37816, 0.614037],.5],*)
(*dashedline[\[Chi]DND[\[Delta]2,\[Tau]D],\[Tau]D,RGBColor[0.560181, 0.691569, 0.194885],.5]*)
(*}*)
(*];*)


(* ::Input:: *)
(*resetparams;*)
(*partshares=Plot[{*)
(*\[Chi]choice[\[Chi],\[Delta]2,\[Tau]D,\[Tau]F],*)
(*\[Chi]choice[\[Chi],\[Delta]1,\[Tau]D,\[Tau]F]*)
(*},*)
(*{\[Chi],0,1},*)
(*PlotRange->{{-.02,1.02},{0,.82}},*)
(*(*PlotLabel\[Rule]"Subscript[\[Delta], 1]="<>ToString[\[Delta]1]<>" Subscript[\[Delta], 2]="<>ToString[\[Delta]2],*)*)
(*PlotStyle->({opa75,#}&/@{RGBColor[0.560181, 0.691569, 0.194885],RGBColor[0.647624, 0.37816, 0.614037]}),FrameLabel->{"Regional content requirement (\!\(\*SubscriptBox[\(\[Chi]\), \(R\)]\))","Regional part share (\[Chi])"},*)
(*Epilog-> {*)
(*Text["\!\(\*SubscriptBox[\(\[Delta]\), \(1\)]\)="<>ToString[\[Delta]1],{0,\[Chi]minD[\[Delta]1]},{-1,-1}],*)
(*Text["\!\(\*SubscriptBox[\(\[Delta]\), \(2\)]\)="<>ToString[\[Delta]2],{0,\[Chi]minD[\[Delta]2]},{-1,-1}]*)
(*}*)
(*];*)


(* ::Input:: *)
(*SetDirectory[ParentDirectory[NotebookDirectory[]]<>"/Plots_JIE_rev/Mathematica"];*)
(*Export["AssemblyCostPenalty_ChiR.pdf",costratio];*)
(*Export["AssemblyPartShare_ChiR.pdf",partshares];*)
